export const DEFAULT_PORTFOLIO = {
  owner: {
    name:     'Rahul Babariya',
    tagline:  'Photographer & Videography Provider',
    bio:      'Capturing life\'s most precious moments through the lens. Owner of Aurpix Studio & Dada Media.',
    photo:    '',
    phone:    '',
    whatsapp: '',
    email:    '',
    address:  'Gujarat, India',
  },
  businesses: {
    aurpix: {
      name:        'Aurpix Studio',
      tagline:     'Studio Photography Specialists',
      description: 'Baby Shoot\nFamily Shoot\nMaternity Shoot\nModeling Shoot\nProducing Shoot\nPodcast Shoot\nMarketing Reel Shoot\nPhoto Frame',
      logo:        '',
      services: [
        { name: 'Baby Shoot',             description: 'Themed baby shoots with props & soft lighting',        price: 'Contact for pricing' },
        { name: 'Family Shoot',           description: 'Professional family & group portraits',                price: 'Contact for pricing' },
        { name: 'Maternity Shoot',        description: 'Elegant indoor maternity photography',                 price: 'Contact for pricing' },
        { name: 'Modeling Shoot',         description: 'Creative fashion & modeling photography sessions',     price: 'Contact for pricing' },
        { name: 'Producing Shoot',        description: 'Professional product & production photography',        price: 'Contact for pricing' },
        { name: 'Podcast Shoot',          description: 'Studio podcast video & photo coverage',               price: 'Contact for pricing' },
        { name: 'Marketing Reel Shoot',   description: 'Short-form video reels for social media marketing',   price: 'Contact for pricing' },
        { name: 'Photo Frame',            description: 'Custom framed portrait photography',                   price: 'Contact for pricing' },
      ],
      gallery:     [],
      socialLinks: [],
    },
    dada: {
      name:        'Dada Media',
      tagline:     'Wedding & Event Photography',
      description: 'Wedding Shoot\nPre-Wedding Shoot\nEngagement Shoot\nMaternity Shoot\nCorporate Shoot\nDharmik Event\nOutdoor Baby Shoot\nLED Screen\nLive Program',
      logo:        '',
      services: [
        { name: 'Wedding Shoot',          description: 'Full wedding day coverage with cinematic editing',     price: 'Contact for pricing' },
        { name: 'Pre-Wedding Shoot',      description: 'Creative outdoor pre-wedding photography',             price: 'Contact for pricing' },
        { name: 'Engagement Shoot',       description: 'Romantic engagement ceremony photography',             price: 'Contact for pricing' },
        { name: 'Maternity Shoot',        description: 'Outdoor & studio maternity photography',               price: 'Contact for pricing' },
        { name: 'Corporate Shoot',        description: 'Professional corporate events & headshots',            price: 'Contact for pricing' },
        { name: 'Dharmik Event',          description: 'Religious & cultural ceremony documentation',          price: 'Contact for pricing' },
        { name: 'Outdoor Baby Shoot',     description: 'Natural light outdoor baby & child photography',       price: 'Contact for pricing' },
        { name: 'LED Screen',             description: 'LED screen setup & display for events',                price: 'Contact for pricing' },
        { name: 'Live Program',           description: 'Live event coverage & streaming',                      price: 'Contact for pricing' },
      ],
      gallery:     [],
      socialLinks: [],
    },
  },
  socialLinks: [
    { platform: 'instagram', label: 'Instagram',  url: '', icon: 'FaInstagram'  },
    { platform: 'facebook',  label: 'Facebook',   url: '', icon: 'FaFacebook'   },
    { platform: 'youtube',   label: 'YouTube',    url: '', icon: 'FaYoutube'    },
    { platform: 'whatsapp',  label: 'WhatsApp',   url: '', icon: 'FaWhatsapp'   },
  ],
};
