import {
    FaWhatsapp,
    FaInstagram,
    FaFacebook,
    FaTwitter,
    FaLinkedin,
    FaYoutube,
    FaTiktok,
    FaSnapchat,
    FaTelegram,
    FaPinterest,
    FaGlobe,
    FaEnvelope,
    FaPhone,
    FaMapMarkerAlt,
    FaHome,
    FaBuilding,
    FaStore,
    FaShoppingCart,
    FaShoppingBag,
    FaLink,
    FaCamera,
    FaMusic,
    FaHeart,
    FaStar,
    FaUser,
    FaUsers,
    FaCoffee,
    FaUtensils,
    FaPizzaSlice,
    FaHamburger,
    FaIceCream,
    FaBirthdayCake,
    FaWineGlass,
    FaCocktail,
    FaCar,
    FaBicycle,
    FaPlane,
    FaTrain,
    FaBus,
    FaTaxi,
    FaTruck,
    FaMotorcycle,
    FaShip,
    FaGamepad,
    FaFilm,
    FaBook,
    FaGraduationCap,
    FaBriefcase,
    FaLaptop,
    FaMobileAlt,
    FaTabletAlt,
    FaDesktop,
    FaKeyboard,
    FaHeadphones,
    FaMicrophone,
    FaVideo,
    FaPaintBrush,
    FaPalette,
    FaCut,
    FaHammer,
    FaWrench,
    FaTools,
    FaMedkit,
    FaStethoscope,
    FaPills,
    FaSyringe,
    FaDumbbell,
    FaRunning,
    FaSwimmer,
    FaFootballBall,
    FaBasketballBall,
    FaBaseballBall,
    FaVolleyballBall,
    FaTree,
    FaLeaf,
    FaSeedling,
    FaPaw,
    FaDog,
    FaCat,
    FaHorse,
    FaFish,
    FaDragon,
    FaGift,
    FaBell,
    FaBullhorn,
    FaCalendar,
    FaClock,
    FaChartLine,
    FaChartBar,
    FaChartPie,
    FaCalculator,
    FaClipboard,
    FaClipboardCheck,
    FaFileAlt,
    FaFolder,
    FaCloud,
    FaDatabase,
    FaServer,
    FaLock,
    FaUnlock,
    FaKey,
    FaShieldAlt,
    FaCreditCard,
    FaDollarSign,
    FaMoneyBill,
    FaCoins,
    FaReceipt,
    FaHandHoldingUsd,
    FaMapPin,
    FaMap,
    FaCompass,
    FaGlobeAmericas,
    FaEllipsisH,
    FaPrint,
} from 'react-icons/fa';

import {
    FiPhone,
    FiMail,
    FiMapPin,
    FiGlobe,
    FiExternalLink,
    FiLink as FiLinkIcon,
} from 'react-icons/fi';

import {
    HiOutlineLocationMarker,
    HiOutlineOfficeBuilding,
    HiOutlineShoppingBag,
} from 'react-icons/hi';

import {
    MdLocationOn,
    MdEmail,
    MdPhone,
    MdBusiness,
    MdStorefront,
    MdRestaurant,
    MdLocalCafe,
    MdLocalBar,
    MdLocalHospital,
    MdLocalPharmacy,
    MdFitnessCenter,
    MdSpa,
    MdLocalLaundryService,
    MdDirectionsCar,
    MdSchool,
    MdWork,
} from 'react-icons/md';

export const iconMap = {
    // Social Media
    'FaWhatsapp': FaWhatsapp,
    'FaInstagram': FaInstagram,
    'FaFacebook': FaFacebook,
    'FaTwitter': FaTwitter,
    'FaLinkedin': FaLinkedin,
    'FaYoutube': FaYoutube,
    'FaTiktok': FaTiktok,
    'FaSnapchat': FaSnapchat,
    'FaTelegram': FaTelegram,
    'FaPinterest': FaPinterest,

    // Contact
    'FaEnvelope': FaEnvelope,
    'FaPhone': FaPhone,
    'FiPhone': FiPhone,
    'FiMail': FiMail,
    'MdEmail': MdEmail,
    'MdPhone': MdPhone,

    // Location
    'FaMapMarkerAlt': FaMapMarkerAlt,
    'FaMapPin': FaMapPin,
    'FaMap': FaMap,
    'FiMapPin': FiMapPin,
    'HiOutlineLocationMarker': HiOutlineLocationMarker,
    'MdLocationOn': MdLocationOn,

    // Website/Links
    'FaGlobe': FaGlobe,
    'FaLink': FaLink,
    'FiGlobe': FiGlobe,
    'FiExternalLink': FiExternalLink,
    'FiLinkIcon': FiLinkIcon,

    // Business
    'FaHome': FaHome,
    'FaBuilding': FaBuilding,
    'FaStore': FaStore,
    'FaBriefcase': FaBriefcase,
    'HiOutlineOfficeBuilding': HiOutlineOfficeBuilding,
    'MdBusiness': MdBusiness,
    'MdStorefront': MdStorefront,
    'MdWork': MdWork,

    // Shopping
    'FaShoppingCart': FaShoppingCart,
    'FaShoppingBag': FaShoppingBag,
    'HiOutlineShoppingBag': HiOutlineShoppingBag,

    // Food & Beverage
    'FaCoffee': FaCoffee,
    'FaUtensils': FaUtensils,
    'FaPizzaSlice': FaPizzaSlice,
    'FaHamburger': FaHamburger,
    'FaIceCream': FaIceCream,
    'FaBirthdayCake': FaBirthdayCake,
    'FaWineGlass': FaWineGlass,
    'FaCocktail': FaCocktail,
    'MdRestaurant': MdRestaurant,
    'MdLocalCafe': MdLocalCafe,
    'MdLocalBar': MdLocalBar,

    // Healthcare
    'FaMedkit': FaMedkit,
    'FaStethoscope': FaStethoscope,
    'FaPills': FaPills,
    'FaSyringe': FaSyringe,
    'MdLocalHospital': MdLocalHospital,
    'MdLocalPharmacy': MdLocalPharmacy,

    // Fitness & Wellness
    'FaDumbbell': FaDumbbell,
    'FaRunning': FaRunning,
    'FaSwimmer': FaSwimmer,
    'MdFitnessCenter': MdFitnessCenter,
    'MdSpa': MdSpa,

    // Transportation
    'FaCar': FaCar,
    'FaBicycle': FaBicycle,
    'FaPlane': FaPlane,
    'FaTrain': FaTrain,
    'FaBus': FaBus,
    'FaTaxi': FaTaxi,
    'FaTruck': FaTruck,
    'FaMotorcycle': FaMotorcycle,
    'FaShip': FaShip,
    'MdDirectionsCar': MdDirectionsCar,

    // Technology
    'FaLaptop': FaLaptop,
    'FaMobileAlt': FaMobileAlt,
    'FaTabletAlt': FaTabletAlt,
    'FaDesktop': FaDesktop,
    'FaKeyboard': FaKeyboard,
    'FaPrint': FaPrint,

    // Entertainment
    'FaGamepad': FaGamepad,
    'FaFilm': FaFilm,
    'FaMusic': FaMusic,
    'FaCamera': FaCamera,
    'FaVideo': FaVideo,
    'FaHeadphones': FaHeadphones,
    'FaMicrophone': FaMicrophone,

    // Sports
    'FaFootballBall': FaFootballBall,
    'FaBasketballBall': FaBasketballBall,
    'FaBaseballBall': FaBaseballBall,
    'FaVolleyballBall': FaVolleyballBall,

    // Education
    'FaBook': FaBook,
    'FaGraduationCap': FaGraduationCap,
    'MdSchool': MdSchool,

    // Art & Design
    'FaPaintBrush': FaPaintBrush,
    'FaPalette': FaPalette,
    'FaCut': FaCut,

    // Tools
    'FaHammer': FaHammer,
    'FaWrench': FaWrench,
    'FaTools': FaTools,

    // Nature
    'FaTree': FaTree,
    'FaLeaf': FaLeaf,
    'FaSeedling': FaSeedling,
    'FaPaw': FaPaw,
    'FaDog': FaDog,
    'FaCat': FaCat,
    'FaHorse': FaHorse,
    'FaFish': FaFish,
    'FaDragon': FaDragon,

    // General
    'FaUser': FaUser,
    'FaUsers': FaUsers,
    'FaHeart': FaHeart,
    'FaStar': FaStar,
    'FaGift': FaGift,
    'FaBell': FaBell,
    'FaBullhorn': FaBullhorn,
    'FaCalendar': FaCalendar,
    'FaClock': FaClock,
    'FaEllipsisH': FaEllipsisH,

    // Finance
    'FaCreditCard': FaCreditCard,
    'FaDollarSign': FaDollarSign,
    'FaMoneyBill': FaMoneyBill,
    'FaCoins': FaCoins,
    'FaHandHoldingUsd': FaHandHoldingUsd,

    // Misc
    'FaLock': FaLock,
    'FaUnlock': FaUnlock,
    'FaKey': FaKey,
    'FaShieldAlt': FaShieldAlt,
    'FaCloud': FaCloud,
    'FaDatabase': FaDatabase,
    'FaServer': FaServer,
    'FaCompass': FaCompass,
    'FaGlobeAmericas': FaGlobeAmericas,
    'MdLocalLaundryService': MdLocalLaundryService,
};

export const iconCategories = {
    'Social Media': [
        { name: 'WhatsApp',  icon: 'FaWhatsapp'  },
        { name: 'Instagram', icon: 'FaInstagram' },
        { name: 'Facebook',  icon: 'FaFacebook'  },
        { name: 'Twitter',   icon: 'FaTwitter'   },
        { name: 'LinkedIn',  icon: 'FaLinkedin'  },
        { name: 'YouTube',   icon: 'FaYoutube'   },
        { name: 'TikTok',    icon: 'FaTiktok'    },
        { name: 'Snapchat',  icon: 'FaSnapchat'  },
        { name: 'Telegram',  icon: 'FaTelegram'  },
        { name: 'Pinterest', icon: 'FaPinterest' },
    ],
    'Contact': [
        { name: 'Email',          icon: 'FaEnvelope'  },
        { name: 'Phone',          icon: 'FaPhone'     },
        { name: 'Mobile',         icon: 'FaMobileAlt' },
        { name: 'Mail (Outline)', icon: 'FiMail'      },
        { name: 'Phone (Outline)',icon: 'FiPhone'     },
    ],
    'Location': [
        { name: 'Map Marker',          icon: 'FaMapMarkerAlt'         },
        { name: 'Map Pin',             icon: 'FaMapPin'               },
        { name: 'Map',                 icon: 'FaMap'                  },
        { name: 'Location',            icon: 'MdLocationOn'           },
        { name: 'Location (Outline)',  icon: 'FiMapPin'               },
    ],
    'Website': [
        { name: 'Globe',         icon: 'FaGlobe'        },
        { name: 'Link',          icon: 'FaLink'         },
        { name: 'External Link', icon: 'FiExternalLink' },
        { name: 'Website',       icon: 'FiGlobe'        },
    ],
    'Business': [
        { name: 'Home',       icon: 'FaHome'                },
        { name: 'Building',   icon: 'FaBuilding'            },
        { name: 'Store',      icon: 'FaStore'               },
        { name: 'Office',     icon: 'HiOutlineOfficeBuilding'},
        { name: 'Business',   icon: 'MdBusiness'            },
        { name: 'Storefront', icon: 'MdStorefront'          },
        { name: 'Briefcase',  icon: 'FaBriefcase'           },
    ],
    'Food & Drink': [
        { name: 'Coffee',    icon: 'FaCoffee'      },
        { name: 'Restaurant',icon: 'FaUtensils'    },
        { name: 'Pizza',     icon: 'FaPizzaSlice'  },
        { name: 'Burger',    icon: 'FaHamburger'   },
        { name: 'Ice Cream', icon: 'FaIceCream'    },
        { name: 'Cake',      icon: 'FaBirthdayCake'},
        { name: 'Wine',      icon: 'FaWineGlass'   },
        { name: 'Cocktail',  icon: 'FaCocktail'    },
        { name: 'Cafe',      icon: 'MdLocalCafe'   },
        { name: 'Bar',       icon: 'MdLocalBar'    },
    ],
    'Health': [
        { name: 'Medical Kit', icon: 'FaMedkit'       },
        { name: 'Hospital',    icon: 'MdLocalHospital'},
        { name: 'Fitness',     icon: 'FaDumbbell'     },
        { name: 'Spa',         icon: 'MdSpa'          },
        { name: 'Running',     icon: 'FaRunning'      },
    ],
    'Travel': [
        { name: 'Car',        icon: 'FaCar'        },
        { name: 'Bicycle',    icon: 'FaBicycle'    },
        { name: 'Plane',      icon: 'FaPlane'      },
        { name: 'Train',      icon: 'FaTrain'      },
        { name: 'Bus',        icon: 'FaBus'        },
        { name: 'Motorcycle', icon: 'FaMotorcycle' },
        { name: 'Ship',       icon: 'FaShip'       },
    ],
    'General': [
        { name: 'User',      icon: 'FaUser'     },
        { name: 'Users',     icon: 'FaUsers'    },
        { name: 'Heart',     icon: 'FaHeart'    },
        { name: 'Star',      icon: 'FaStar'     },
        { name: 'Gift',      icon: 'FaGift'     },
        { name: 'Bell',      icon: 'FaBell'     },
        { name: 'Calendar',  icon: 'FaCalendar' },
        { name: 'Clock',     icon: 'FaClock'    },
        { name: 'Camera',    icon: 'FaCamera'   },
        { name: 'Music',     icon: 'FaMusic'    },
        { name: 'Book',      icon: 'FaBook'     },
        { name: 'More',      icon: 'FaEllipsisH'},
    ],
};

export const getIconComponent = (iconName) => {
    return iconMap[iconName] || FaLink;
};
